### ISSUE TITLE
Add Placeholder Ellipsis Styling?

### ISSUE THREAD

**Issue by hryanjones** [JosephusPaye/Keen-UI#298]
Would it be possible to add placeholder `text-overflow: ellipsis` styles to **autocomplete**, **datepicker**, and **textbox** per [this article](https://davidwalsh.name/placeholder-overflow)? It doesn't seem super hard, so I could probably do this and send a CR if you agree it's okay to do.

**Comment by JosephusPaye** [comment]
Yeah, go for it.

**Comment by JosephusPaye** [comment]
It seems like covering all browsers would require something like this:

```css
[placeholder]{
    text-overflow:ellipsis;
}
::-webkit-input-placeholder { /* Chrome/Opera/Safari */
    text-overflow:ellipsis;
}
::-moz-placeholder { /* Firefox 19+ */
    text-overflow:ellipsis;
}
:-ms-input-placeholder { /* IE 10+ */
    text-overflow:ellipsis;
}
:-moz-placeholder { /* Firefox 18- */
    text-overflow:ellipsis;
}
```

Closing for now as this one really doesn't seem to be worth the added code.
