### ISSUE TITLE
UiCheckbox border-radius doesn't hide overflow

### ISSUE THREAD

**Issue by hyvyys** [JosephusPaye/Keen-UI#471]
![image](https://user-images.githubusercontent.com/20814638/66278701-f2ad3500-e8ab-11e9-8265-11fccbbabe5f.png)
On background other than white it doesn't look too good.

**Comment by hyvyys** [comment]
```css
.ui-checkbox__checkmark {
  border-radius: 0.125rem;
}
```

fixes it

**Comment by JosephusPaye** [comment]
The artifact is actually the white background from the `.ui-checkbox__checkbox` div. `::before` is rounded with the border radius, but the div itself isn't.

Can be fixed without overriding the `border-radius` by:

```css
.ui-checkbox__checkmark {
    border-radius: 0.125rem;
}
```

PR welcome 🙂
